# ROCm provider discovery and flags

include_guard(GLOBAL)

set(ALPAKA_HAS_ROCBLAS OFF)
set(ALPAKA_HAS_MIOPEN OFF)

find_package(rocblas QUIET)
if(rocblas_FOUND)
    set(ALPAKA_HAS_ROCBLAS ON)
    message(STATUS "rocBLAS found: ${rocblas_DIR}")
endif()

# Try both capitalization variants used by different distros
find_package(MIOpen QUIET)
if(MIOpen_FOUND)
    set(ALPAKA_HAS_MIOPEN ON)
    message(STATUS "MIOpen (capitalized) found: ${MIOpen_DIR}")
else()
    find_package(miopen QUIET)
    if(miopen_FOUND)
        set(ALPAKA_HAS_MIOPEN ON)
        message(STATUS "miopen found: ${miopen_DIR}")
    endif()
endif()

if(TARGET alpaka_target_hip)
    if(ALPAKA_HAS_ROCBLAS)
        target_link_libraries(alpaka_target_hip INTERFACE roc::rocblas)
        target_compile_definitions(alpaka_target_hip INTERFACE ALPAKA_HAS_ROCBLAS)
    endif()
    if(ALPAKA_HAS_MIOPEN)
        # miopen cmake exports can vary (MIOpen, MIOpen::MIOpen, or miopen). Try all common names.
        if(TARGET MIOpen::MIOpen)
            target_link_libraries(alpaka_target_hip INTERFACE MIOpen::MIOpen)
        elseif(TARGET MIOpen)
            target_link_libraries(alpaka_target_hip INTERFACE MIOpen)
        elseif(TARGET miopen)
            target_link_libraries(alpaka_target_hip INTERFACE miopen)
        else()
            message(WARNING "ALPAKA_HAS_MIOPEN is ON but no known MIOpen CMake target was found; linking may fail")
        endif()
        target_compile_definitions(alpaka_target_hip INTERFACE ALPAKA_HAS_MIOPEN)
    endif()
endif()
